// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWC1cfMjHBQY3yTr5OOxLbdylflmIuBUg',
    appId: '1:272342051919:web:4d46fdbf1e700ca7aace3a',
    messagingSenderId: '272342051919',
    projectId: 'inviration-5246e',
    authDomain: 'inviration-5246e.firebaseapp.com',
    storageBucket: 'inviration-5246e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRQHMCKeInrE4N33ran-Vv9mVBfiP-YyM',
    appId: '1:272342051919:android:94a1eaa747ec9137aace3a',
    messagingSenderId: '272342051919',
    projectId: 'inviration-5246e',
    storageBucket: 'inviration-5246e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA48QNP-lL7QNxd4Ww4gJig4yKMClScgEs',
    appId: '1:272342051919:ios:b1700ec04d500911aace3a',
    messagingSenderId: '272342051919',
    projectId: 'inviration-5246e',
    storageBucket: 'inviration-5246e.firebasestorage.app',
    iosBundleId: 'com.example.onesignal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA48QNP-lL7QNxd4Ww4gJig4yKMClScgEs',
    appId: '1:272342051919:ios:b1700ec04d500911aace3a',
    messagingSenderId: '272342051919',
    projectId: 'inviration-5246e',
    storageBucket: 'inviration-5246e.firebasestorage.app',
    iosBundleId: 'com.example.onesignal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWC1cfMjHBQY3yTr5OOxLbdylflmIuBUg',
    appId: '1:272342051919:web:f64ab102b7613f88aace3a',
    messagingSenderId: '272342051919',
    projectId: 'inviration-5246e',
    authDomain: 'inviration-5246e.firebaseapp.com',
    storageBucket: 'inviration-5246e.firebasestorage.app',
  );
}
